# Generated by Django 5.2.4 on 2025-07-14 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(db_column='descripcion_categoria', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(db_column='id_estado', primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='estado', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='PermisoAcceso',
            fields=[
                ('id_permiso_acceso', models.IntegerField(db_column='id_permiso_acceso', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='Rol', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Permisos Acceso',
                'db_table': 'permisos_acceso',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(db_column='id_empresa', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(db_column='nombre_empresa', max_length=200)),
                ('direccion', models.CharField(db_column='Direccion', max_length=200)),
                ('fecha_registros', models.DateField(db_column='Fecha_registros')),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=100)),
                ('pais', models.CharField(db_column='pais', max_length=100)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.categoria')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.estado')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='id_producto', primary_key=True, serialize=False)),
                ('producto', models.CharField(db_column='producto', max_length=200)),
                ('Url', models.URLField(db_column='Url', max_length=500)),
                ('iframe', models.URLField(db_column='iframe', max_length=500)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.estado')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='nombres', max_length=200)),
                ('correo', models.EmailField(db_column='correo', max_length=255, unique=True)),
                ('contrasena', models.CharField(db_column='contrasena', max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_permiso_acceso', models.ForeignKey(db_column='id_permiso_acceso', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.permisoacceso')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.usuario')),
            ],
            options={
                'verbose_name_plural': 'Detalle Producto',
                'db_table': 'detalle_producto',
                'unique_together': {('id_producto', 'id_usuario')},
            },
        ),
    ]
