# Generated by Django 5.2.4 on 2025-07-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='iframe',
            field=models.CharField(db_column='iframe', max_length=500),
        ),
    ]
