# Generated by Django 5.2.4 on 2025-07-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0002_alter_producto_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardVentasColtrade',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('id_punto_venta', models.CharField(db_column='id_punto_venta', max_length=150)),
                ('punto_venta', models.CharField(db_column='punto_venta', max_length=150)),
                ('dinero_entregado', models.IntegerField(db_column='dinero_entregado')),
                ('cantidad_entregada', models.IntegerField(db_column='cantidad_entregada')),
                ('fecha_entrega', models.DateField(db_column='fecha_entrega')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Ventas Coltrade',
                'db_table': 'dashboard_ventas_coltrade',
            },
        ),
        migrations.CreateModel(
            name='DashboardVentasDataflow',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('id_punto_venta', models.CharField(db_column='id_punto_venta', max_length=150)),
                ('punto_venta', models.CharField(db_column='punto_venta', max_length=150)),
                ('dinero_entregado', models.IntegerField(db_column='dinero_entregado')),
                ('cantidad_entregada', models.IntegerField(db_column='cantidad_entregada')),
                ('fecha_entrega', models.DateField(db_column='fecha_entrega')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Ventas Dataflow',
                'db_table': 'dashboard_ventas_dataflow',
            },
        ),
        migrations.CreateModel(
            name='DashboardVentasLoop',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('id_punto_venta', models.CharField(db_column='id_punto_venta', max_length=150)),
                ('punto_venta', models.CharField(db_column='punto_venta', max_length=150)),
                ('dinero_entregado', models.IntegerField(db_column='dinero_entregado')),
                ('cantidad_entregada', models.IntegerField(db_column='cantidad_entregada')),
                ('fecha_entrega', models.DateField(db_column='fecha_entrega')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Ventas Loop',
                'db_table': 'dashboard_ventas_loop',
            },
        ),
    ]
