# Generated by Django 5.2.4 on 2025-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0003_dashboardventascoltrade_dashboardventasdataflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id_plan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
