# Generated by Django 5.2.4 on 2025-07-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0004_empresa_id_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id_plan', models.IntegerField(db_column='id_plan', primary_key=True, serialize=False)),
                ('tipo_plan', models.CharField(db_column='producto', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Planes',
                'db_table': 'planes',
            },
        ),
    ]
