# Generated by Django 5.2.4 on 2025-07-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0005_tipoplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='id_plan',
        ),
    ]
