# Generated by Django 5.2.4 on 2025-07-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0006_remove_empresa_id_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id_plan',
            field=models.ForeignKey(db_column='id_plan', default=1, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.tipoplan'),
            preserve_default=False,
        ),
    ]
