# Generated by Django 5.2.4 on 2025-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0007_empresa_id_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(blank=True, db_column='tipo_producto', max_length=200, null=True),
        ),
    ]
