# Generated by Django 5.2.4 on 2025-07-17 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0009_alter_producto_tipo_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProductoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.usuario')),
            ],
            options={
                'verbose_name_plural': 'Detalle Producto Vendido',
                'db_table': 'detalle_producto_vendido',
                'unique_together': {('id_producto', 'id_usuario')},
            },
        ),
    ]
