# Generated by Django 5.2.4 on 2025-07-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0010_detalleproductovendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(blank=True, db_column='Correo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_hora_pago',
            field=models.DateTimeField(blank=True, db_column='Fecha_hora_pago', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pagina_web',
            field=models.URLField(blank=True, db_column='Pagina_web', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='prefijo_pais',
            field=models.CharField(blank=True, db_column='Prefijo_pais', max_length=5, null=True),
        ),
    ]
