# Generated by Django 5.2.4 on 2025-07-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0011_empresa_correo_empresa_fecha_hora_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, db_column='apellidos', max_length=200, null=True),
        ),
    ]
