# Generated by Django 5.2.4 on 2025-07-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0013_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
    ]
