# Generated by Django 5.2.4 on 2025-07-23 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0014_alter_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id_empresa',
            field=models.AutoField(db_column='id_empresa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='appdataflowai.empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
    ]
