# Generated by Django 5.2.4 on 2025-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0015_alter_empresa_id_empresa_alter_pagos_id_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(db_column='id_categoria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estado',
            name='id_estado',
            field=models.AutoField(db_column='id_estado', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permisoacceso',
            name='id_permiso_acceso',
            field=models.AutoField(db_column='id_permiso_acceso', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(db_column='id_producto', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipoplan',
            name='id_plan',
            field=models.AutoField(db_column='id_plan', primary_key=True, serialize=False),
        ),
    ]
