# Generated by Django 5.2.4 on 2025-07-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0016_alter_categoria_id_categoria_alter_estado_id_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria_producto',
            field=models.CharField(choices=[('software', 'Software'), ('servicio', 'Servicio'), ('herramienta', 'Herramienta')], db_column='categoria_producto', default='software', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('suscripcion', 'Suscripción'), ('pago_unico', 'Pago Único'), ('demo', 'Versión Demo')], db_column='tipo_producto', max_length=30, null=True),
        ),
    ]
