# Generated by Django 5.2.4 on 2025-07-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0017_producto_categoria_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', default=1, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.estado'),
            preserve_default=False,
        ),
    ]
