# Generated by Django 5.2.4 on 2025-07-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0018_remove_usuario_estado_usuario_id_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplan',
            name='valor_plan',
            field=models.DecimalField(blank=True, db_column='valor_plan', decimal_places=2, max_digits=10, null=True),
        ),
    ]
