# Generated by Django 5.2.4 on 2025-07-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0019_tipoplan_valor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='id_plan',
            field=models.ForeignKey(db_column='id_plan', default=1, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.tipoplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagos',
            name='ingreso',
            field=models.DecimalField(db_column='ingreso', decimal_places=2, max_digits=10),
        ),
    ]
