# Generated by Django 5.2.4 on 2025-07-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0020_pagos_id_plan_alter_pagos_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardVentas',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('id_punto_venta', models.CharField(blank=True, db_column='id_punto_venta', max_length=150, null=True)),
                ('punto_venta', models.CharField(blank=True, db_column='punto_venta', max_length=150, null=True)),
                ('canal', models.CharField(blank=True, db_column='canal', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=100, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True)),
                ('cantidad_vendida', models.IntegerField(blank=True, db_column='cantidad_vendida', null=True)),
                ('dinero_vendido', models.DecimalField(blank=True, db_column='dinero_vendido', decimal_places=2, max_digits=15, null=True)),
                ('ticket_promedio', models.DecimalField(blank=True, db_column='ticket_promedio', decimal_places=2, max_digits=10, null=True)),
                ('unidades_promocionadas', models.IntegerField(blank=True, db_column='unidades_promocionadas', null=True)),
                ('descuento_total', models.DecimalField(blank=True, db_column='descuento_total', decimal_places=2, max_digits=12, null=True)),
                ('numero_transacciones', models.IntegerField(blank=True, db_column='numero_transacciones', null=True)),
                ('devoluciones', models.IntegerField(blank=True, db_column='devoluciones', null=True)),
                ('dinero_devoluciones', models.DecimalField(blank=True, db_column='dinero_devoluciones', decimal_places=2, max_digits=12, null=True)),
                ('fecha_venta', models.DateField(blank=True, db_column='fecha_venta', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='mes', null=True)),
                ('anio', models.IntegerField(blank=True, db_column='anio', null=True)),
                ('dia_semana', models.CharField(blank=True, db_column='dia_semana', max_length=20, null=True)),
                ('hora', models.TimeField(blank=True, db_column='hora', null=True)),
                ('sku', models.CharField(blank=True, db_column='sku', max_length=100, null=True)),
                ('nombre_producto', models.CharField(blank=True, db_column='nombre_producto', max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, db_column='categoria', max_length=100, null=True)),
                ('subcategoria', models.CharField(blank=True, db_column='subcategoria', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, db_column='marca', max_length=100, null=True)),
                ('tipo_cliente', models.CharField(blank=True, db_column='tipo_cliente', max_length=100, null=True)),
                ('segmento_cliente', models.CharField(blank=True, db_column='segmento_cliente', max_length=100, null=True)),
                ('genero_cliente', models.CharField(blank=True, db_column='genero_cliente', max_length=20, null=True)),
                ('edad_cliente', models.IntegerField(blank=True, db_column='edad_cliente', null=True)),
                ('utilidad_bruta', models.DecimalField(blank=True, db_column='utilidad_bruta', decimal_places=2, max_digits=15, null=True)),
                ('costo_total', models.DecimalField(blank=True, db_column='costo_total', decimal_places=2, max_digits=15, null=True)),
                ('margen_utilidad', models.DecimalField(blank=True, db_column='margen_utilidad', decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Ventas',
                'db_table': 'dashboard_ventas',
            },
        ),
    ]
