# Generated by Django 5.2.4 on 2025-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0021_dashboardventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Url',
            field=models.URLField(blank=True, db_column='Url', max_length=500, null=True),
        ),
    ]
