# Generated by Django 5.2.4 on 2025-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0022_alter_producto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Url',
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, db_column='slug', max_length=250, null=True, unique=True),
        ),
    ]
