# Generated by Django 5.2.4 on 2025-07-31 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0023_remove_producto_url_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardventasdataflow',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', default=59, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardventasdataflow',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto'),
        ),
    ]
