# Generated by Django 5.2.4 on 2025-07-31 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0026_dashboardventasdataflow_id_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardventasdataflow',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', editable=False, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa'),
        ),
        migrations.AlterField(
            model_name='dashboardventasdataflow',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto'),
        ),
    ]
