# Generated by Django 5.2.4 on 2025-07-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0027_alter_dashboardventasdataflow_id_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardventasdataflow',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='dashboardventasdataflow',
            name='id_producto',
        ),
    ]
