# Generated by Django 5.2.4 on 2025-07-31 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0029_dashboardfinanzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCompras',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, db_column='fecha_compra', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='mes', null=True)),
                ('anio', models.IntegerField(blank=True, db_column='anio', null=True)),
                ('proveedor', models.CharField(blank=True, db_column='proveedor', max_length=255, null=True)),
                ('tipo_proveedor', models.CharField(blank=True, db_column='tipo_proveedor', max_length=100, null=True)),
                ('cantidad_comprada', models.IntegerField(blank=True, db_column='cantidad_comprada', null=True)),
                ('valor_unitario', models.DecimalField(blank=True, db_column='valor_unitario', decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, db_column='valor_total', decimal_places=2, max_digits=18, null=True)),
                ('nombre_producto', models.CharField(blank=True, db_column='nombre_producto', max_length=255, null=True)),
                ('categoria', models.CharField(blank=True, db_column='categoria', max_length=100, null=True)),
                ('subcategoria', models.CharField(blank=True, db_column='subcategoria', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, db_column='marca', max_length=100, null=True)),
                ('condiciones_pago', models.CharField(blank=True, db_column='condiciones_pago', max_length=100, null=True)),
                ('tiempo_entrega_dias', models.IntegerField(blank=True, db_column='tiempo_entrega_dias', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Compras',
                'db_table': 'dashboard_compras',
            },
        ),
    ]
