# Generated by Django 5.2.4 on 2025-08-19 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0030_dashboardcompras'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSales',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('point_of_sale_id', models.CharField(blank=True, db_column='point_of_sale_id', max_length=150, null=True)),
                ('point_of_sale', models.CharField(blank=True, db_column='point_of_sale', max_length=150, null=True)),
                ('channel', models.CharField(blank=True, db_column='channel', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, db_column='quantity_sold', null=True)),
                ('sales_amount', models.DecimalField(blank=True, db_column='sales_amount', decimal_places=2, max_digits=15, null=True)),
                ('average_ticket', models.DecimalField(blank=True, db_column='average_ticket', decimal_places=2, max_digits=10, null=True)),
                ('promoted_units', models.IntegerField(blank=True, db_column='promoted_units', null=True)),
                ('total_discount', models.DecimalField(blank=True, db_column='total_discount', decimal_places=2, max_digits=12, null=True)),
                ('number_transactions', models.IntegerField(blank=True, db_column='number_transactions', null=True)),
                ('returns', models.IntegerField(blank=True, db_column='returns', null=True)),
                ('return_amount', models.DecimalField(blank=True, db_column='return_amount', decimal_places=2, max_digits=12, null=True)),
                ('sale_date', models.DateField(blank=True, db_column='sale_date', null=True)),
                ('month', models.IntegerField(blank=True, db_column='month', null=True)),
                ('year', models.IntegerField(blank=True, db_column='year', null=True)),
                ('weekday', models.CharField(blank=True, db_column='weekday', max_length=20, null=True)),
                ('hour', models.TimeField(blank=True, db_column='hour', null=True)),
                ('sku', models.CharField(blank=True, db_column='sku', max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, db_column='product_name', max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_column='category', max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, db_column='subcategory', max_length=100, null=True)),
                ('brand', models.CharField(blank=True, db_column='brand', max_length=100, null=True)),
                ('customer_type', models.CharField(blank=True, db_column='customer_type', max_length=100, null=True)),
                ('customer_segment', models.CharField(blank=True, db_column='customer_segment', max_length=100, null=True)),
                ('customer_gender', models.CharField(blank=True, db_column='customer_gender', max_length=20, null=True)),
                ('customer_age', models.IntegerField(blank=True, db_column='customer_age', null=True)),
                ('gross_profit', models.DecimalField(blank=True, db_column='gross_profit', decimal_places=2, max_digits=15, null=True)),
                ('total_cost', models.DecimalField(blank=True, db_column='total_cost', decimal_places=2, max_digits=15, null=True)),
                ('profit_margin', models.DecimalField(blank=True, db_column='profit_margin', decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Sales',
                'db_table': 'dashboard_sales',
            },
        ),
    ]
