# Generated by Django 5.2.4 on 2025-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0031_dashboardsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link_pb',
            field=models.URLField(blank=True, db_column='link_pb', max_length=500, null=True),
        ),
    ]
