# Generated by Django 5.2.4 on 2025-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0032_producto_link_pb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_area', models.AutoField(db_column='id_area', primary_key=True, serialize=False)),
                ('area_trabajo', models.CharField(db_column='area_trabajo', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria_producto',
            field=models.CharField(choices=[('javascript', 'Javascript'), ('power', 'Power')], db_column='categoria_producto', default='software', max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('publico', 'Publico'), ('privado', 'Privado')], db_column='tipo_producto', max_length=30, null=True),
        ),
    ]
