# Generated by Django 5.2.4 on 2025-09-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0034_usuario_id_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_area',
            field=models.ForeignKey(db_column='id_area', default=1, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.areas'),
            preserve_default=False,
        ),
    ]
