# Generated by Django 5.2.4 on 2025-09-08 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0035_producto_id_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name': 'Detalle Empresa Dashboard',
                'verbose_name_plural': 'Detalle Empresa Dashboard',
                'db_table': 'detalle_empresa_dashboard',
                'unique_together': {('producto', 'empresa')},
            },
        ),
    ]
