# Generated by Django 5.2.4 on 2025-09-09 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0036_empresadashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSalesreview',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('mes', models.CharField(db_column='MES', max_length=20)),
                ('mes_numero', models.IntegerField(db_column='MES#')),
                ('semana', models.CharField(db_column='SEMANA', max_length=10)),
                ('dia_compra', models.CharField(db_column='DIA DE COMPRA', max_length=20)),
                ('fecha_compra', models.DateField(db_column='FECHA DE COMPRA')),
                ('fecha_envio', models.DateField(db_column='FECHA ENVIO')),
                ('numero_pedido', models.CharField(db_column='Nº PEDIDO', max_length=50)),
                ('numero_oc', models.CharField(db_column='Nº OC', max_length=50)),
                ('estado', models.CharField(db_column='ESTADO', max_length=50)),
                ('linea', models.CharField(db_column='LINEA', max_length=50)),
                ('fuente', models.CharField(db_column='FUENTE', max_length=50)),
                ('sku_enviado', models.CharField(db_column='SKU ENVIADO', max_length=50)),
                ('categoria', models.CharField(db_column='CATEGORIA', max_length=50)),
                ('producto', models.CharField(db_column='PRODUCTO', max_length=100)),
                ('precio_unidad_antes_iva', models.DecimalField(db_column='PRECIO DE LA UNIDAD ANTES DE IVA', decimal_places=2, max_digits=12)),
                ('unidades', models.IntegerField(db_column='UNIDADES')),
                ('ingresos_antes_iva', models.DecimalField(db_column='INGRESOS ANTES DE IVA', decimal_places=2, max_digits=100)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Sales Review',
                'db_table': 'dashboard_salesreview',
            },
        ),
    ]
