# Generated by Django 5.2.4 on 2025-09-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0037_dashboardsalesreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_corto',
            field=models.CharField(db_column='nombre_corto', default='Coltrade', max_length=100),
            preserve_default=False,
        ),
    ]
