# Generated by Django 5.2.4 on 2025-09-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0038_empresa_nombre_corto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(db_column='id_ticket', primary_key=True, serialize=False)),
                ('correo', models.EmailField(db_column='correo', max_length=255)),
                ('asunto', models.CharField(db_column='asunto', max_length=255)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('solucionada', 'Solucionada'), ('en_solucion', 'Está siendo revisada')], db_column='estado', default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_cierre', models.DateTimeField(blank=True, db_column='fecha_cierre', null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.usuario')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
            },
        ),
    ]
