# Generated by Django 5.2.4 on 2025-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0039_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comentario',
            field=models.TextField(blank=True, db_column='comentario', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('solucionada', 'Solucionada'), ('en_solucion', 'Está siendo revisada')], db_column='estado', default='creada', max_length=20),
        ),
    ]
