# Generated by Django 5.2.4 on 2025-09-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0040_ticket_comentario_alter_ticket_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoHerramientas',
            fields=[
                ('id_producto_herramienta', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('producto_herramienta', models.CharField(db_column='producto', max_length=200, verbose_name='Nombre del producto')),
                ('tipo_producto', models.CharField(blank=True, choices=[('publico', 'Público'), ('privado', 'Privado')], db_column='tipo_producto', max_length=30, null=True)),
                ('link_producto', models.URLField(blank=True, db_column='link_producto', help_text='URL del recurso (ej. informe Power BI)', max_length=500, null=True)),
                ('id_area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.PROTECT, related_name='productos_herramientas', to='appdataflowai.areas')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='productos_herramientas', to='appdataflowai.estado')),
            ],
            options={
                'verbose_name': 'Producto Herramienta',
                'verbose_name_plural': 'Productos Herramientas',
                'db_table': 'productos_herramientas',
                'ordering': ['producto_herramienta'],
            },
        ),
    ]
