# Generated by Django 5.2.4 on 2025-09-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0041_productoherramientas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProductoHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(db_column='id_producto_herramienta', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='appdataflowai.productoherramientas')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='appdataflowai.usuario')),
            ],
            options={
                'verbose_name': 'Detalle Producto Herramientas',
                'verbose_name_plural': 'Detalles de Productos',
                'db_table': 'detalle_producto_herramientas',
                'unique_together': {('id_producto', 'id_usuario')},
            },
        ),
    ]
