# Generated by Django 5.2.4 on 2025-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0042_detalleproductoherramientas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproductoherramientas',
            options={'verbose_name': 'Detalle Producto Herramientas', 'verbose_name_plural': 'Detalle Producto Herramientas'},
        ),
        migrations.AddField(
            model_name='producto',
            name='link_dashboard_externo',
            field=models.URLField(blank=True, db_column='link_dashboard_externo', help_text='URL del dashboard externos', max_length=500, null=True),
        ),
    ]
