# Generated by Django 5.2.4 on 2025-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0043_alter_detalleproductoherramientas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria_producto',
            field=models.CharField(choices=[('javascript', 'Javascript'), ('power', 'Power'), ('externo', 'Informe Externo')], db_column='categoria_producto', default='software', max_length=30),
        ),
    ]
