# Generated by Django 5.2.4 on 2025-10-28 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0044_alter_producto_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosSesion',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(db_column='nombre_empresa', editable=False, max_length=200)),
                ('nombres', models.CharField(db_column='nombres', editable=False, max_length=200)),
                ('fecha_inicio_sesion', models.DateTimeField(db_column='fecha_inicio_sesion', default=django.utils.timezone.now)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='registros_sesiones', to='appdataflowai.empresa')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='registros_sesiones_usuario', to='appdataflowai.usuario')),
            ],
            options={
                'verbose_name_plural': 'Registros de Sesión',
                'db_table': 'registros_sesion',
            },
        ),
    ]
