# Generated by Django 5.2.4 on 2025-10-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0044_alter_producto_categoria_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSalesCorporativo',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('orden_compra', models.CharField(db_column='orden_compra', max_length=50)),
                ('fecha', models.DateField(db_column='fecha')),
                ('mes_nombre', models.CharField(blank=True, db_column='mes_nombre', max_length=20, null=True)),
                ('categoria_cliente', models.CharField(blank=True, db_column='categoria_cliente', max_length=100, null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='nombre_cliente', max_length=150, null=True)),
                ('categoria_producto', models.CharField(blank=True, db_column='categoria_producto', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, db_column='marca', max_length=100, null=True)),
                ('producto', models.CharField(blank=True, db_column='producto', max_length=150, null=True)),
                ('estado_cotizacion', models.FloatField(blank=True, db_column='estado_cotizacion', null=True)),
                ('unidades', models.IntegerField(blank=True, db_column='unidades', null=True)),
                ('precio_unitario', models.DecimalField(blank=True, db_column='precio_unitario', decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Sales Corporativo',
                'db_table': 'dashboard_salescorporativo',
            },
        ),
    ]
