# Generated by Django 5.2.4 on 2025-10-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0046_dashboardsalescorporativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSalesCorporativoMetas',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(db_column='ano')),
                ('mes', models.IntegerField(db_column='mes')),
                ('categoria_cliente', models.CharField(blank=True, db_column='categoria_cliente', max_length=100, null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='nombre_cliente', max_length=150, null=True)),
                ('categoria_producto', models.CharField(blank=True, db_column='categoria_producto', max_length=100, null=True)),
                ('meta', models.DecimalField(db_column='meta', decimal_places=2, max_digits=14)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Sales Corporativo Metas',
                'db_table': 'dashboard_salescorporativometas',
                'ordering': ['-ano', '-mes'],
            },
        ),
    ]
