# Generated by Django 5.2.4 on 2025-11-10 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0046_dashboardispventas_dashboardsalescorporativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChurnKpi',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('id_cliente', models.CharField(db_index=True, help_text='ID único del cliente', max_length=64)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_plan', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('otros', 'Otros')], db_index=True, default='standard', max_length=50)),
                ('region', models.CharField(blank=True, db_index=True, help_text='Región o departamento', max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('fecha_ultima_transaccion', models.DateTimeField(blank=True, null=True)),
                ('estado_cliente', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_index=True, default='activo', max_length=10)),
                ('monto_facturado_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Facturación mensual del cliente', max_digits=12, null=True)),
                ('margen_bruto', models.DecimalField(blank=True, decimal_places=4, help_text='Margen bruto (ej: 0.85 para 85%)', max_digits=6, null=True)),
                ('arpu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ARPU')),
                ('churn_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Ingreso perdido por churn', max_digits=12, null=True)),
                ('uso_datos', models.DecimalField(blank=True, decimal_places=3, help_text='Uso de datos (MB/GB según convención)', max_digits=12, null=True)),
                ('numero_quejas', models.IntegerField(default=0)),
                ('pagos_atrasados', models.IntegerField(default=0, help_text='Número de pagos atrasados')),
                ('interacciones_servicio', models.IntegerField(default=0, help_text='Número de contactos con atención al cliente')),
                ('satisfaccion_cliente', models.DecimalField(blank=True, decimal_places=1, help_text='Nivel de satisfacción o NPS (0–10)', max_digits=3, null=True)),
                ('mes', models.DateField(blank=True, help_text='Representa el mes de referencia (ej: 2025-07-01)', null=True)),
                ('clientes_nuevos_mes', models.IntegerField(blank=True, null=True)),
                ('clientes_perdidos_mes', models.IntegerField(blank=True, null=True)),
                ('churn_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de churn mensual', max_digits=7, null=True)),
                ('retention_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de retención mensual', max_digits=7, null=True)),
                ('churn_flag', models.BooleanField(default=False, help_text='True si el cliente se dio de baja')),
                ('probabilidad_churn', models.DecimalField(blank=True, decimal_places=4, help_text='Probabilidad estimada de churn (0–1)', max_digits=5, null=True)),
                ('prediccion_churn', models.BooleanField(blank=True, help_text='Predicción binaria del modelo', null=True)),
                ('margen_predicho', models.DecimalField(blank=True, decimal_places=4, help_text='Margen estimado futuro', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_churn_kpi', to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_churn_kpi', to='appdataflowai.producto')),
            ],
            options={
                'verbose_name': 'Dashboard Churn KPI',
                'verbose_name_plural': 'Dashboard Churn KPIs',
                'db_table': 'dashboard_churn_kpi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_empresa', 'mes'], name='dashboard_c_id_empr_488b8e_idx'), models.Index(fields=['region'], name='dashboard_c_region_7da045_idx'), models.Index(fields=['tipo_plan'], name='dashboard_c_tipo_pl_4409b9_idx'), models.Index(fields=['estado_cliente'], name='dashboard_c_estado__6553c9_idx')],
            },
        ),
    ]
