# Generated by Django 5.2.4 on 2025-11-10 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0047_dashboardchurnkpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChurnRate',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(db_column='id_cliente', db_index=True)),
                ('nombre_cliente', models.CharField(db_column='nombre_cliente', max_length=255)),
                ('tipo_plan', models.CharField(blank=True, choices=[('basico', 'Básico'), ('estandar', 'Estándar'), ('premium', 'Premium')], db_column='tipo_plan', max_length=20, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, db_column='departamento', max_length=100, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, db_column='fecha_contratacion', null=True)),
                ('fecha_baja', models.DateField(blank=True, db_column='fecha_baja', null=True)),
                ('fecha_ultima_transaccion', models.DateField(blank=True, db_column='fecha_ultima_transaccion', null=True)),
                ('estado_cliente', models.CharField(blank=True, choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('inactivo', 'Inactivo')], db_column='estado_cliente', max_length=20, null=True)),
                ('monto_facturado_mensual', models.DecimalField(blank=True, db_column='monto_facturado_mensual', decimal_places=2, max_digits=14, null=True)),
                ('margen_bruto', models.DecimalField(blank=True, db_column='margen_bruto', decimal_places=4, max_digits=12, null=True)),
                ('arpu', models.DecimalField(blank=True, db_column='arpu', decimal_places=2, max_digits=12, null=True)),
                ('numero_quejas', models.IntegerField(db_column='numero_quejas', default=0)),
                ('total_reclamos', models.IntegerField(db_column='total_reclamos', default=0)),
                ('interacciones_servicio', models.IntegerField(db_column='interacciones_servicio', default=0)),
                ('satisfaccion_cliente', models.DecimalField(blank=True, db_column='satisfaccion_cliente', decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('valor_percibido', models.DecimalField(blank=True, db_column='valor_percibido', decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('recomendacion_nps', models.DecimalField(blank=True, db_column='recomendacion_nps', decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('observacion_cliente', models.TextField(blank=True, db_column='observacion_cliente', null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name': 'Dashboard Churn Rate',
                'verbose_name_plural': 'Dashboard Churn Rates',
                'db_table': 'dashboard_churn_rate',
                'ordering': ['-fecha_ultima_transaccion'],
            },
        ),
    ]
