# Generated by Django 5.2.4 on 2025-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0047_dashboardsalescorporativometas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsalescorporativometas',
            name='mes',
            field=models.CharField(blank=True, db_column='mes', max_length=10, null=True),
        ),
    ]
