# Generated by Django 5.2.4 on 2025-11-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0047_dashboardarpu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardarpu',
            options={'ordering': ['-periodo_mes'], 'verbose_name_plural': 'Dashboard ISP ARPU'},
        ),
    ]
