# Generated by Django 5.2.4 on 2025-11-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0048_dashboardchurnrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardChurnKpi',
        ),
    ]
