# Generated by Django 5.2.4 on 2025-10-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0048_alter_dashboardsalescorporativometas_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsalescorporativo',
            name='estado_cotizacion',
            field=models.CharField(blank=True, db_column='estado_cotizacion', max_length=10, null=True),
        ),
    ]
