# Generated by Django 5.2.4 on 2025-11-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0049_alter_dashboardsalescorporativo_estado_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardIspVentas',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(db_column='ano')),
                ('mes', models.CharField(blank=True, db_column='mes', max_length=15, null=True)),
                ('fecha_registro', models.DateField(blank=True, db_column='fecha_registro', null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='nombre_cliente', max_length=150, null=True)),
                ('categoria_cliente', models.CharField(blank=True, db_column='categoria_cliente', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=100, null=True)),
                ('segmento', models.CharField(blank=True, db_column='segmento', max_length=100, null=True)),
                ('nombre_plan', models.CharField(blank=True, db_column='nombre_plan', max_length=150, null=True)),
                ('categoria_plan', models.CharField(blank=True, db_column='categoria_plan', max_length=100, null=True)),
                ('velocidad_mbps', models.DecimalField(blank=True, db_column='velocidad_mbps', decimal_places=2, max_digits=10, null=True)),
                ('precio_mensual', models.DecimalField(blank=True, db_column='precio_mensual', decimal_places=2, max_digits=14, null=True)),
                ('estado_suscripcion', models.CharField(blank=True, db_column='estado_suscripcion', max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, db_column='fecha_inicio', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='fecha_fin', null=True)),
                ('monto_facturado', models.DecimalField(blank=True, db_column='monto_facturado', decimal_places=2, max_digits=14, null=True)),
                ('metodo_pago', models.CharField(blank=True, db_column='metodo_pago', max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard ISP Ventas',
                'db_table': 'dashboard_isp_ventas',
                'ordering': ['-ano', '-mes'],
            },
        ),
    ]
