# Generated by Django 5.2.4 on 2025-11-12 17:00

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0049_delete_dashboardchurnkpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardARPU',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('cliente_id', models.CharField(blank=True, db_column='cliente_id', max_length=100, null=True)),
                ('fecha_evento', models.DateTimeField(blank=True, db_column='fecha_evento', null=True)),
                ('periodo_mes', models.DateField(db_column='periodo_mes')),
                ('tipo_evento', models.CharField(blank=True, db_column='tipo_evento', max_length=50, null=True)),
                ('monto_evento', models.DecimalField(blank=True, db_column='monto_evento', decimal_places=2, max_digits=14, null=True)),
                ('moneda', models.CharField(db_column='moneda', default='COP', max_length=10)),
                ('estado', models.CharField(blank=True, db_column='estado', max_length=20, null=True)),
                ('fecha_alta', models.DateField(blank=True, db_column='fecha_alta', null=True)),
                ('fecha_baja', models.DateField(blank=True, db_column='fecha_baja', null=True)),
                ('tarifa_plan', models.DecimalField(blank=True, db_column='tarifa_plan', decimal_places=2, max_digits=12, null=True)),
                ('velocidad_mbps', models.IntegerField(blank=True, db_column='velocidad_mbps', null=True)),
                ('canal_adquisicion', models.CharField(blank=True, db_column='canal_adquisicion', max_length=50, null=True)),
                ('ingresos_totales', models.DecimalField(db_column='ingresos_totales', decimal_places=2, default=0, max_digits=18)),
                ('mrr', models.DecimalField(db_column='mrr', decimal_places=2, default=0, max_digits=18)),
                ('usuarios_promedio', models.IntegerField(db_column='usuarios_promedio', default=0)),
                ('subs_inicio', models.IntegerField(blank=True, db_column='subs_inicio', null=True)),
                ('subs_final', models.IntegerField(blank=True, db_column='subs_final', null=True)),
                ('arpu', models.DecimalField(db_column='arpu', decimal_places=2, default=0, max_digits=14)),
                ('churn', models.DecimalField(blank=True, db_column='churn', decimal_places=6, max_digits=8, null=True)),
                ('promo_id', models.CharField(blank=True, db_column='promo_id', max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, db_column='tags', null=True)),
                ('metadata', models.JSONField(blank=True, db_column='metadata', null=True)),
                ('doc', models.JSONField(blank=True, db_column='doc', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard ISP ARPU',
                'db_table': 'dashboard_arpu',
                'ordering': ['-periodo_mes'],
                'indexes': [models.Index(fields=['id_empresa', 'id_producto', 'periodo_mes'], name='dashboard_a_id_empr_01084e_idx'), models.Index(fields=['id_empresa', 'periodo_mes'], name='dashboard_a_id_empr_308283_idx'), django.contrib.postgres.indexes.GinIndex(fields=['doc'], name='dashboard_arpu_doc_gin')],
            },
        ),
    ]
