# Generated by Django 5.2.4 on 2025-11-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0050_dashboardarpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, related_name='formularios', to='appdataflowai.empresa')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios', to='appdataflowai.usuario')),
            ],
            options={
                'db_table': 'formularios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=512)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de texto'), ('date', 'Fecha'), ('int', 'Número entero'), ('float', 'Número decimal'), ('email', 'Email'), ('select', 'Selección'), ('checkbox', 'Checkbox (múltiple)')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('requerido', models.BooleanField(default=False)),
                ('opciones', models.JSONField(blank=True, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='appdataflowai.formulario')),
            ],
            options={
                'db_table': 'preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='appdataflowai.formulario')),
            ],
            options={
                'db_table': 'respuestas',
                'ordering': ['-fecha'],
            },
        ),
    ]
