# Generated by Django 5.2.4 on 2025-11-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0051_formulario_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='branching',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
