# Generated by Django 5.2.4 on 2025-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0052_pregunta_branching'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproducto',
            name='db_name',
            field=models.CharField(blank=True, db_column='db_name', max_length=255, null=True),
        ),
    ]
