# Generated by Django 5.2.4 on 2025-11-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0053_detalleproducto_db_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='db_name',
            field=models.CharField(blank=True, db_column='db_name', max_length=255, null=True),
        ),
    ]
