# Generated by Django 5.2.4 on 2025-11-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0054_producto_db_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='db_name',
        ),
    ]
