# Generated by Django 5.2.4 on 2025-12-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0055_remove_detalleproducto_db_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTradeInventario',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('fecha_inventario', models.DateField(blank=True, db_column='fecha_inventario', null=True)),
                ('mes', models.CharField(blank=True, choices=[('enero', 'enero'), ('febrero', 'febrero'), ('marzo', 'marzo'), ('abril', 'abril'), ('mayo', 'mayo'), ('junio', 'junio'), ('julio', 'julio'), ('agosto', 'agosto'), ('septiembre', 'septiembre'), ('octubre', 'octubre'), ('noviembre', 'noviembre'), ('diciembre', 'diciembre')], db_column='mes', max_length=15, null=True)),
                ('ano', models.IntegerField(blank=True, db_column='ano', null=True)),
                ('codigo_barras_product', models.CharField(blank=True, db_column='codigo_barras_product', max_length=100, null=True)),
                ('punto_de_venta', models.CharField(blank=True, db_column='punto_de_venta', max_length=150, null=True)),
                ('id_pos', models.CharField(blank=True, db_column='id_pos', max_length=100, null=True)),
                ('sku', models.CharField(blank=True, db_column='sku', max_length=100, null=True)),
                ('producto', models.CharField(blank=True, db_column='producto', max_length=250, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='cantidad', null=True)),
                ('unit_price', models.DecimalField(blank=True, db_column='unit_price', decimal_places=4, max_digits=14, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Trade Inventario',
                'db_table': 'dashboard_trade_inventario',
                'ordering': ['-ano', 'mes', '-fecha_inventario'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTradeMetas',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('mes', models.CharField(blank=True, choices=[('enero', 'enero'), ('febrero', 'febrero'), ('marzo', 'marzo'), ('abril', 'abril'), ('mayo', 'mayo'), ('junio', 'junio'), ('julio', 'julio'), ('agosto', 'agosto'), ('septiembre', 'septiembre'), ('octubre', 'octubre'), ('noviembre', 'noviembre'), ('diciembre', 'diciembre')], db_column='mes', max_length=15, null=True)),
                ('ano', models.IntegerField(blank=True, db_column='ano', null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=100, null=True)),
                ('ean_pvd', models.CharField(blank=True, db_column='ean_pvd', max_length=100, null=True)),
                ('tienda', models.CharField(blank=True, db_column='tienda', max_length=150, null=True)),
                ('meta', models.DecimalField(blank=True, db_column='meta', decimal_places=4, help_text='meta total del mes', max_digits=18, null=True)),
                ('meta_diaria', models.DecimalField(blank=True, db_column='meta_diaria', decimal_places=4, help_text='meta dividida por dias del mes', max_digits=18, null=True)),
                ('meta_semanal', models.DecimalField(blank=True, db_column='meta_semanal', decimal_places=4, help_text='meta dividida por semanas del mes', max_digits=18, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Trade Metas',
                'db_table': 'dashboard_trade_metas',
                'ordering': ['-ano', 'mes'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTradeVentas',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, db_column='fecha_venta', null=True)),
                ('sem', models.IntegerField(blank=True, db_column='sem', help_text='numero de semana de la fecha_venta', null=True)),
                ('mes', models.CharField(blank=True, db_column='mes', help_text='mes en texto derivado de fecha_venta', max_length=15, null=True)),
                ('ano', models.IntegerField(blank=True, db_column='ano', help_text='ano derivado de fecha_venta', null=True)),
                ('id_pos', models.CharField(blank=True, db_column='id_pos', max_length=100, null=True)),
                ('punto_de_venta', models.CharField(blank=True, db_column='punto_de_venta', max_length=150, null=True)),
                ('codigo_barras_product', models.CharField(blank=True, db_column='codigo_barras_product', max_length=100, null=True)),
                ('sku', models.CharField(blank=True, db_column='sku', max_length=100, null=True)),
                ('producto', models.CharField(blank=True, db_column='producto', max_length=250, null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='cantidad', null=True)),
                ('unit_price', models.DecimalField(blank=True, db_column='unit_price', decimal_places=4, max_digits=14, null=True)),
                ('total_sellthru', models.DecimalField(blank=True, db_column='total_sellthru', decimal_places=4, max_digits=18, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Dashboard Trade Ventas',
                'db_table': 'dashboard_trade_ventas',
                'ordering': ['-ano', '-mes', '-fecha_venta'],
            },
        ),
    ]
