# Generated by Django 5.2.4 on 2025-12-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0056_dashboardtradeinventario_dashboardtrademetas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardContext',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('chat_input', models.TextField()),
                ('session_id', models.CharField(max_length=100)),
                ('dashboard_name', models.CharField(max_length=200)),
                ('dashboard_context', models.TextField()),
                ('tables', models.JSONField()),
                ('formularios_id', models.JSONField(blank=True, null=True)),
                ('empresa_id', models.IntegerField()),
            ],
        ),
    ]
