# Generated by Django 5.2.4 on 2025-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0057_dashboardcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='dashboard_context',
            field=models.TextField(blank=True, db_column='dashboard_context', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='formularios_id',
            field=models.JSONField(blank=True, db_column='formularios_id', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tables',
            field=models.JSONField(blank=True, db_column='tables', null=True),
        ),
    ]
