# Generated by Django 5.2.4 on 2025-12-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0058_producto_dashboard_context_producto_formularios_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardcontext',
            name='chat_input',
        ),
    ]
