# Generated by Django 5.2.4 on 2026-01-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0059_remove_dashboardcontext_chat_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashDfProductos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('valor_producto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
            ],
            options={
                'db_table': 'dash_df_productos',
            },
        ),
        migrations.CreateModel(
            name='DashDfTiendas',
            fields=[
                ('id_tienda', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tienda', models.CharField(max_length=50)),
                ('direccion_tienda', models.CharField(max_length=50)),
                ('horario_tienda', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('canal', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
            ],
            options={
                'db_table': 'dash_df_tiendas',
            },
        ),
        migrations.CreateModel(
            name='DashDfMetas',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('meta_cantidad', models.IntegerField()),
                ('meta_dinero', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_meta', models.DateField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.dashdfproductos')),
                ('id_tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.dashdftiendas')),
            ],
            options={
                'db_table': 'dash_df_metas',
            },
        ),
        migrations.CreateModel(
            name='DashDfInventarios',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('inventario_cantidad', models.IntegerField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.dashdfproductos')),
                ('id_tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.dashdftiendas')),
            ],
            options={
                'db_table': 'dash_df_inventarios',
            },
        ),
        migrations.CreateModel(
            name='DashDfVentas',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vendida', models.IntegerField()),
                ('dinero_vendido', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_venta', models.DateField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.dashdfproductos')),
                ('id_tienda', models.ForeignKey(db_column='id_tienda', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.dashdftiendas')),
            ],
            options={
                'db_table': 'dash_df_ventas',
            },
        ),
    ]
