# Generated by Django 5.2.4 on 2026-02-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0060_dashdfproductos_dashdftiendas_dashdfmetas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooSaleFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_odoo_id', models.IntegerField()),
                ('partner_odoo_id', models.IntegerField(blank=True, null=True)),
                ('user_odoo_id', models.IntegerField(blank=True, null=True)),
                ('company_odoo_id', models.IntegerField(blank=True, null=True)),
                ('invoice_odoo_id', models.IntegerField(blank=True, null=True)),
                ('product_odoo_id', models.IntegerField(blank=True, null=True)),
                ('sale_reference', models.CharField(max_length=100)),
                ('invoice_name', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField()),
                ('commitment_date', models.DateField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('partner_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('canal', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('product_uom_qty', models.FloatField(default=0)),
                ('qty_invoiced', models.FloatField(default=0)),
                ('qty_delivered', models.FloatField(default=0)),
                ('price_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_state', models.CharField(max_length=50)),
                ('invoice_state', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
