# Generated by Django 5.2.4 on 2026-02-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0061_odoosaleflat'),
    ]

    operations = [
        migrations.AddField(
            model_name='odoosaleflat',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', default=1, on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa'),
            preserve_default=False,
        ),
    ]
