# Generated by Django 5.2.4 on 2026-02-05 18:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0062_odoosaleflat_id_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsBrokers',
            fields=[
                ('id_lead', models.AutoField(db_column='id_lead', primary_key=True, serialize=False)),
                ('nombre_lead', models.CharField(db_column='nombre_lead', max_length=200)),
                ('correo', models.EmailField(blank=True, db_column='correo', max_length=255)),
                ('persona_de_contacto', models.CharField(blank=True, db_column='persona_de_contacto', max_length=200)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=30)),
                ('pais', models.CharField(blank=True, db_column='pais', max_length=100)),
                ('industria', models.CharField(blank=True, db_column='industria', max_length=150)),
                ('tamano_empresa', models.CharField(blank=True, choices=[('PE', 'Pequeña'), ('ME', 'Mediana'), ('GR', 'Grande')], db_column='tamano_empresa', max_length=2)),
                ('ticket_estimado', models.DecimalField(blank=True, db_column='ticket_estimado', decimal_places=2, max_digits=14, null=True)),
                ('moneda_ticket', models.CharField(blank=True, db_column='moneda_ticket', default='USD', max_length=10)),
                ('probabilidad_cierre', models.DecimalField(blank=True, db_column='probabilidad_cierre', decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('campo_etiqueta', models.CharField(blank=True, db_column='campo_etiqueta', max_length=100)),
                ('fuente_lead', models.CharField(blank=True, db_column='fuente_lead', max_length=150)),
                ('comentarios', models.TextField(blank=True, db_column='comentarios')),
                ('etapa', models.CharField(choices=[('lead_prospecto', 'lead prospecto'), ('lead_prospecto_calificado', 'lead prospecto calificado'), ('lead_calificado', 'lead calificado'), ('lead_demo', 'lead demo'), ('propuesta_enviada', 'propuesta enviada'), ('lead_ganado', 'lead ganado'), ('lead_perdido', 'lead perdido')], db_column='etapa', default='lead_prospecto', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Leads Brokers',
                'db_table': 'leads_brokers',
            },
        ),
        migrations.CreateModel(
            name='FacturacionLeadsBrokers',
            fields=[
                ('numero_factura', models.IntegerField(db_column='numero_factura', primary_key=True, serialize=False)),
                ('fecha_facturacion', models.DateField(db_column='fecha_facturacion')),
                ('valor_facturado', models.DecimalField(db_column='valor_facturado', decimal_places=2, max_digits=14)),
                ('comision_percent', models.DecimalField(db_column='comision_percent', decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('id_lead', models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='appdataflowai.leadsbrokers')),
            ],
            options={
                'verbose_name_plural': 'Facturación Leads Brokers',
                'db_table': 'facturacion_leads_brokers',
            },
        ),
        migrations.CreateModel(
            name='PagosBrokersLeads',
            fields=[
                ('id_pago', models.AutoField(db_column='id_pago', primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(db_column='fecha_pago')),
                ('valor_pagado', models.DecimalField(db_column='valor_pagado', decimal_places=2, max_digits=14)),
                ('estado', models.BooleanField(db_column='estado', default=False)),
                ('numero_factura', models.ForeignKey(db_column='numero_factura', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='appdataflowai.facturacionleadsbrokers')),
            ],
            options={
                'verbose_name_plural': 'Pagos Brokers Leads',
                'db_table': 'pagos_brokers_leads',
            },
        ),
        migrations.CreateModel(
            name='UsuariosBrokers',
            fields=[
                ('id_broker', models.AutoField(db_column='id_broker', primary_key=True, serialize=False)),
                ('numero_telefono', models.CharField(blank=True, db_column='numero_telefono', max_length=30)),
                ('pais_residencia', models.CharField(blank=True, db_column='pais_residencia', max_length=100)),
                ('entidad_financiera', models.CharField(blank=True, db_column='entidad_financiera', max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, db_column='numero_cuenta', max_length=100)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('AH', 'Cuenta de ahorros'), ('CO', 'Cuenta corriente'), ('OT', 'Otro')], db_column='tipo_cuenta', max_length=2)),
                ('codigo_swift', models.CharField(blank=True, db_column='codigo_swift', max_length=50)),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('NIT', 'NIT'), ('PA', 'Pasaporte')], db_column='tipo_identificacion', max_length=4)),
                ('numero_identificacion', models.CharField(blank=True, db_column='numero_identificacion', max_length=60)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='brokers', to='appdataflowai.usuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios Brokers',
                'db_table': 'usuarios_brokers',
            },
        ),
        migrations.AddField(
            model_name='leadsbrokers',
            name='id_broker',
            field=models.ForeignKey(db_column='id_broker', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='appdataflowai.usuariosbrokers'),
        ),
        migrations.AddField(
            model_name='facturacionleadsbrokers',
            name='id_broker',
            field=models.ForeignKey(db_column='id_broker', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='appdataflowai.usuariosbrokers'),
        ),
    ]
