# Generated by Django 5.2.4 on 2026-02-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0063_leadsbrokers_facturacionleadsbrokers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialesDataflow',
            fields=[
                ('id_tutorial', models.AutoField(db_column='id_tutorial', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('enlace', models.URLField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tutoriales DataFlow',
                'db_table': 'tutoriales_data_flow',
            },
        ),
    ]
