# Generated by Django 5.2.4 on 2026-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0065_alter_leadsbrokers_etapa_canalesbluetti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasbluetti',
            name='producto',
            field=models.CharField(blank=True, db_column='producto', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ventasbluetti',
            name='sku',
            field=models.CharField(blank=True, db_column='sku', max_length=100, null=True),
        ),
    ]
