# Generated by Django 5.2.4 on 2026-03-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0066_ventasbluetti_producto_ventasbluetti_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='conetcom_campanas',
            fields=[
                ('id_campana', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_campana', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('canal', models.CharField(blank=True, choices=[('retail', 'Retail - Grandes superficies'), ('reseller_wh', 'Reseller - Mayorista'), ('reseller_hw', 'Reseller - Ferreterías'), ('ecommerce', 'E-commerce'), ('other', 'Otro')], max_length=30, null=True)),
                ('segmento_objetivo', models.CharField(blank=True, max_length=200, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_campanas',
            },
        ),
        migrations.CreateModel(
            name='conetcom_clientes',
            fields=[
                ('id_cliente', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_alta_cliente', models.DateField()),
                ('estado_cliente', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('residencial', 'Residencial'), ('empresarial', 'Empresarial'), ('mayorista', 'Mayorista')], max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('region_departamento', models.CharField(max_length=100)),
                ('canal_adquisicion', models.CharField(choices=[('venta_directa', 'Venta directa'), ('web', 'Web'), ('aliado', 'Aliado'), ('call_center', 'Call center')], max_length=30)),
                ('id_plan_contratado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_plan_contratado', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion_contrato', models.DateField(blank=True, null=True)),
                ('indicador_vip', models.BooleanField(default=False)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_clientes',
            },
        ),
        migrations.CreateModel(
            name='conetcom_facturacion',
            fields=[
                ('id_factura', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_total_facturado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado_factura', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('vencida', 'Vencida')], max_length=20)),
                ('valor_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='appdataflowai.conetcom_clientes')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_facturacion',
            },
        ),
        migrations.CreateModel(
            name='conetcom_interacciones_campanas',
            fields=[
                ('id_interaccion', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('abrio_mensaje', models.BooleanField(default=False)),
                ('hizo_clic', models.BooleanField(default=False)),
                ('genero_conversion', models.BooleanField(default=False)),
                ('ingresos_generados', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('id_campana', models.ForeignKey(db_column='id_campana', on_delete=django.db.models.deletion.CASCADE, to='appdataflowai.conetcom_campanas')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='appdataflowai.conetcom_clientes')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_interacciones_campanas',
            },
        ),
        migrations.CreateModel(
            name='conetcom_pagos',
            fields=[
                ('id_pago', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medio_de_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_pago', models.CharField(blank=True, choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('fallido', 'Fallido')], max_length=20, null=True)),
                ('metodo_de_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='appdataflowai.conetcom_clientes')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_factura_asociada', models.ForeignKey(blank=True, db_column='id_factura_asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdataflowai.conetcom_facturacion')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_pagos',
            },
        ),
        migrations.CreateModel(
            name='conetcom_planes',
            fields=[
                ('id_plan', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=150)),
                ('velocidad_descarga_mbps', models.FloatField()),
                ('velocidad_subida_mbps', models.FloatField()),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duracion_minima_contrato_meses', models.IntegerField()),
                ('tipo_tecnologia', models.CharField(max_length=100)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_planes',
            },
        ),
        migrations.CreateModel(
            name='conetcom_tickets_soporte',
            fields=[
                ('id_ticket', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('area_agente_asignado', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria_ticket', models.CharField(choices=[('instalacion', 'Instalación'), ('interrupcion', 'Interrupción'), ('facturacion', 'Facturación'), ('otros', 'Otros')], max_length=30)),
                ('prioridad', models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, null=True)),
                ('indicador_incumplimiento_sla', models.BooleanField(default=False)),
                ('tiempo_resolucion', models.DurationField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='appdataflowai.conetcom_clientes')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_tickets_soporte',
            },
        ),
        migrations.CreateModel(
            name='conetcom_trafico_consumo',
            fields=[
                ('id_registro', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('consumo_descarga_gb', models.FloatField(blank=True, null=True)),
                ('consumo_subida_gb', models.FloatField(blank=True, null=True)),
                ('velocidad_pico_mbps', models.FloatField(blank=True, null=True)),
                ('velocidad_promedio_mbps', models.FloatField(blank=True, null=True)),
                ('numero_sesiones', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='appdataflowai.conetcom_clientes')),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'db_table': 'conetcom_trafico_consumo',
            },
        ),
    ]
