# Generated by Django 5.2.4 on 2026-03-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0067_conetcom_campanas_conetcom_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conetcom_clientes',
            name='nombre_cliente',
            field=models.CharField(blank=True, db_column='nombre_cliente', max_length=150, null=True),
        ),
    ]
