# Generated by Django 5.2.4 on 2026-03-06 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0068_conetcom_clientes_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conetcom_clientes',
            name='id_plan_contratado',
            field=models.ForeignKey(blank=True, db_column='id_plan_contratado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdataflowai.conetcom_planes'),
        ),
    ]
