# Generated by Django 5.2.4 on 2026-04-07 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdataflowai', '0069_alter_conetcom_clientes_id_plan_contratado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosLoopTotek',
            fields=[
                ('id_registro', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateField(blank=True, db_column='fecha_servicio', null=True)),
                ('mes', models.CharField(blank=True, db_column='mes', max_length=20, null=True)),
                ('ano', models.IntegerField(blank=True, db_column='ano', null=True)),
                ('tipo_empresa', models.CharField(blank=True, choices=[('DIRECTO', 'Directo'), ('RETAIL', 'Retail')], db_column='tipo_empresa', max_length=50, null=True)),
                ('categoria_servicio', models.CharField(blank=True, db_column='categoria_servicio', max_length=100, null=True)),
                ('descripcion_servicio', models.CharField(blank=True, db_column='descripcion_servicio', max_length=500, null=True)),
                ('cantidad_instalada', models.IntegerField(db_column='cantidad_instalada', default=0)),
                ('estado_servicio', models.CharField(choices=[('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado'), ('NO_INSTALADO', 'No Instalado')], db_column='estado_servicio', default='FINALIZADO', max_length=50)),
                ('motivo_cancelacion', models.CharField(blank=True, db_column='motivo_cancelacion', max_length=200, null=True)),
                ('motivo_reprogramacion', models.CharField(blank=True, db_column='motivo_reprogramacion', max_length=200, null=True)),
                ('satisfaccion_cliente', models.IntegerField(blank=True, choices=[(1, '1 - Muy insatisfecho'), (2, '2 - Insatisfecho'), (3, '3 - Neutral'), (4, '4 - Satisfecho'), (5, '5 - Muy satisfecho')], db_column='satisfaccion_cliente', null=True)),
                ('ciudad_principal', models.CharField(blank=True, choices=[('BOGOTA', 'Bogotá'), ('MEDELLIN', 'Medellín'), ('CALI', 'Cali'), ('BARRANQUILLA', 'Barranquilla'), ('CARTAGENA', 'Cartagena'), ('VILLAVICENCIO', 'Villavicencio'), ('YOPAL', 'Yopal'), ('GIRARDOT', 'Girardot'), ('IBAGUE', 'Ibagué'), ('ARMENIA', 'Armenia'), ('NEIVA', 'Neiva'), ('MANIZALES', 'Manizales'), ('PEREIRA', 'Pereira'), ('BUCARAMANGA', 'Bucaramanga'), ('CUCUTA', 'Cúcuta'), ('SANTA_MARTA', 'Santa Marta'), ('VALLEDUPAR', 'Valledupar'), ('TUNJA', 'Tunja'), ('SINCELEJO', 'Sincelejo'), ('MONTERIA', 'Montería'), ('OTRA', 'Otra')], db_column='ciudad_principal', max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, db_column='ciudad', max_length=150, null=True)),
                ('municipio_sector', models.CharField(blank=True, db_column='municipio_sector', max_length=200, null=True)),
                ('codigo_ot', models.CharField(blank=True, db_column='codigo_ot', max_length=50, null=True)),
                ('nombre_instalador', models.CharField(blank=True, db_column='nombre_instalador', max_length=250, null=True)),
                ('notas', models.TextField(blank=True, db_column='notas', null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.empresa')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='appdataflowai.producto')),
            ],
            options={
                'verbose_name_plural': 'Servicios Loop Totek',
                'db_table': 'servicios_loop_totek',
                'ordering': ['-fecha_servicio'],
            },
        ),
    ]
